apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
	name: frontend
spec:
  selector:
	matchLabels:
  	app: frontend
  replicas: 1
  template:
	metadata:
  	labels:
    	app: frontend
	spec:
  	containers:
    	- name: frontend-container
      	image: efrei2023/frontend-panel:2002
      	imagePullPolicy: Always
ports:
        	- containerPort: 80
      	env:
        	- name: POSTGRES_PASSWORD
          	value: postgres
        	- name: POSTGRES_USER
          	value: postgres
  	imagePullSecrets:
    	- name: efrei2023
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
	app: frontend
spec:
  type: NodePort
  ports:
	- port: 80
  targetPort: 8000
  selector:
	app: frontend
